# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from standings_Dialog import Ui_Dialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnFuel = QtWidgets.QPushButton(self.centralwidget)
        self.btnFuel.setGeometry(QtCore.QRect(340, 290, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(14)
        self.btnFuel.setFont(font)
        self.btnFuel.setObjectName("btnFuel")
        self.lblBienvenida = QtWidgets.QLabel(self.centralwidget)
        self.lblBienvenida.setGeometry(QtCore.QRect(170, 40, 481, 91))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(20)
        self.lblBienvenida.setFont(font)
        self.lblBienvenida.setObjectName("lblBienvenida")
        self.btnStandings = QtWidgets.QPushButton(self.centralwidget)
        self.btnStandings.setGeometry(QtCore.QRect(340, 200, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(14)
        self.btnStandings.setFont(font)
        self.btnStandings.setObjectName("btnStandings")
        self.btnStandings.clicked.connect(self.openStandings)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnFuel.setText(_translate("MainWindow", "Fuel Calculator"))
        self.lblBienvenida.setText(_translate("MainWindow", "Elija los complementos que desea iniciar"))
        self.btnStandings.setText(_translate("MainWindow", "Standings"))
    
    def openStandings(self):
        # Crear la instancia de la clase Standings
        ventana_standings = QtWidgets.QMainWindow()
        ui2 = Ui_Dialog()
        ui2.setupUi(ventana_standings)
        ventana_standings.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
