# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'standings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import irsdk, operator

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1042, 809)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 70, 791, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblCar = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblCar.setObjectName("lblCar")
        self.horizontalLayout_6.addWidget(self.lblCar)
        self.lblSOF = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblSOF.setObjectName("lblSOF")
        self.horizontalLayout_6.addWidget(self.lblSOF)
        self.lblCircuito = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblCircuito.setObjectName("lblCircuito")
        self.horizontalLayout_6.addWidget(self.lblCircuito)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lblPosition_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblPosition_1.setObjectName("lblPosition_1")
        self.horizontalLayout_7.addWidget(self.lblPosition_1)
        self.lblID_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblID_1.setObjectName("lblID_1")
        self.horizontalLayout_7.addWidget(self.lblID_1)
        self.lblNombre_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblNombre_1.setObjectName("lblNombre_1")
        self.horizontalLayout_7.addWidget(self.lblNombre_1)
        self.lblFastLap_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblFastLap_1.setObjectName("lblFastLap_1")
        self.horizontalLayout_7.addWidget(self.lblFastLap_1)
        self.lblLastLap_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblLastLap_1.setObjectName("lblLastLap_1")
        self.horizontalLayout_7.addWidget(self.lblLastLap_1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lblPosition_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblPosition_2.setObjectName("lblPosition_2")
        self.horizontalLayout_10.addWidget(self.lblPosition_2)
        self.lblID_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblID_2.setObjectName("lblID_2")
        self.horizontalLayout_10.addWidget(self.lblID_2)
        self.lblNombre_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblNombre_2.setObjectName("lblNombre_2")
        self.horizontalLayout_10.addWidget(self.lblNombre_2)
        self.lblFastLap_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblFastLap_2.setObjectName("lblFastLap_2")
        self.horizontalLayout_10.addWidget(self.lblFastLap_2)
        self.lblLastLap_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblLastLap_2.setObjectName("lblLastLap_2")
        self.horizontalLayout_10.addWidget(self.lblLastLap_2)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lblPosition_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblPosition_3.setObjectName("lblPosition_3")
        self.horizontalLayout_9.addWidget(self.lblPosition_3)
        self.lblID_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblID_3.setObjectName("lblID_3")
        self.horizontalLayout_9.addWidget(self.lblID_3)
        self.lblNombre_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblNombre_3.setObjectName("lblNombre_3")
        self.horizontalLayout_9.addWidget(self.lblNombre_3)
        self.lblFastLap_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblFastLap_3.setObjectName("lblFastLap_3")
        self.horizontalLayout_9.addWidget(self.lblFastLap_3)
        self.lblLastLap_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblLastLap_3.setObjectName("lblLastLap_3")
        self.horizontalLayout_9.addWidget(self.lblLastLap_3)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lblPosition_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblPosition_4.setObjectName("lblPosition_4")
        self.horizontalLayout_8.addWidget(self.lblPosition_4)
        self.lblID_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblID_4.setObjectName("lblID_4")
        self.horizontalLayout_8.addWidget(self.lblID_4)
        self.lblNombre_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblNombre_4.setObjectName("lblNombre_4")
        self.horizontalLayout_8.addWidget(self.lblNombre_4)
        self.lblFastLap_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblFastLap_4.setObjectName("lblFastLap_4")
        self.horizontalLayout_8.addWidget(self.lblFastLap_4)
        self.lblLastLap_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblLastLap_4.setObjectName("lblLastLap_4")
        self.horizontalLayout_8.addWidget(self.lblLastLap_4)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblPosition_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblPosition_5.setObjectName("lblPosition_5")
        self.horizontalLayout_5.addWidget(self.lblPosition_5)
        self.lblID_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblID_5.setObjectName("lblID_5")
        self.horizontalLayout_5.addWidget(self.lblID_5)
        self.lblNombre_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblNombre_5.setObjectName("lblNombre_5")
        self.horizontalLayout_5.addWidget(self.lblNombre_5)
        self.lblFastLap_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblFastLap_5.setObjectName("lblFastLap_5")
        self.horizontalLayout_5.addWidget(self.lblFastLap_5)
        self.lblLastLap_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblLastLap_5.setObjectName("lblLastLap_5")
        self.horizontalLayout_5.addWidget(self.lblLastLap_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1042, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblCar.setText(_translate("MainWindow", "Coche"))
        self.lblSOF.setText(_translate("MainWindow", "SOF"))
        self.lblCircuito.setText(_translate("MainWindow", "Circuito"))
        self.lblPosition_1.setText(_translate("MainWindow", "Position"))
        self.lblID_1.setText(_translate("MainWindow", "#ID"))
        self.lblNombre_1.setText(_translate("MainWindow", "Nombre"))
        self.lblFastLap_1.setText(_translate("MainWindow", "FastestLap"))
        self.lblLastLap_1.setText(_translate("MainWindow", "LastLap"))
        self.lblPosition_2.setText(_translate("MainWindow", "Position"))
        self.lblID_2.setText(_translate("MainWindow", "#ID"))
        self.lblNombre_2.setText(_translate("MainWindow", "Nombre"))
        self.lblFastLap_2.setText(_translate("MainWindow", "FastestLap"))
        self.lblLastLap_2.setText(_translate("MainWindow", "LastLap"))
        self.lblPosition_3.setText(_translate("MainWindow", "Position"))
        self.lblID_3.setText(_translate("MainWindow", "#ID"))
        self.lblNombre_3.setText(_translate("MainWindow", "Nombre"))
        self.lblFastLap_3.setText(_translate("MainWindow", "FastestLap"))
        self.lblLastLap_3.setText(_translate("MainWindow", "LastLap"))
        self.lblPosition_4.setText(_translate("MainWindow", "Position"))
        self.lblID_4.setText(_translate("MainWindow", "#ID"))
        self.lblNombre_4.setText(_translate("MainWindow", "Nombre"))
        self.lblFastLap_4.setText(_translate("MainWindow", "FastestLap"))
        self.lblLastLap_4.setText(_translate("MainWindow", "LastLap"))
        self.lblPosition_5.setText(_translate("MainWindow", "Position"))
        self.lblID_5.setText(_translate("MainWindow", "#ID"))
        self.lblNombre_5.setText(_translate("MainWindow", "Nombre"))
        self.lblFastLap_5.setText(_translate("MainWindow", "FastestLap"))
        self.lblLastLap_5.setText(_translate("MainWindow", "LastLap"))

    def cargarDatos(self):
        # Conecta con el simulador
        ir = irsdk.IRSDK()
        ir.startup()

        # Obtén los datos del estado de la carrera
        estado_carrera = ir['SessionState']

        # Verifica si la carrera está activa
        if estado_carrera == irsdk.SessionState.racing:
            # Obtén los datos de la posición de los participantes
            participantes = ir['SessionInfo']['Sessions'][0]['ResultsPositions']
            
            # Ordena los participantes por su posición en la carrera
            participantes_ordenados = sorted(participantes, key=operator.itemgetter('Position'))
        else:
            print('No esta abierto iRacing')

        #Mostramos los resultados en los label
        def agregar_cero_si_es_necesario(valor):
            return f"{valor:02d}"
        
        #Mostrar SOF
        totaliRating = 0
        for i in ir['DriverInfo']['Drivers']:
            totaliRating += [i][0]['IRating']
        SOF = totaliRating / len(participantes_ordenados)
        self.lblSOF.setText("SOF: {0:.0f}".format(SOF))

        #Mostrar vehiculo
        id = ir['DriverInfo']['DriverCarIdx']
        self.lblCar.setText(ir['DriverInfo']['Drivers'][id]['CarScreenName'])

        #Mostrar Circuito
        self.lblCircuito.setText(ir['WeekendInfo']['TrackDisplayName'])
        #Participante 1
        self.lblPosition_1.setText(str(participantes_ordenados[0]['Position']))
        self.lblID_1.setText(str(participantes_ordenados[0]['CarIdx']))
        self.lblNombre_1.setText(ir['DriverInfo']['Drivers'][participantes_ordenados[0]['CarIdx']]['UserName'])
        minutos, segundos_sobrantes = divmod(float(participantes_ordenados[0]['FastestTime']), 60)
        self.lblFastLap_1.setText(agregar_cero_si_es_necesario(int(minutos)) + ":{0:.3f}".format(segundos_sobrantes))
        minutos, segundos_sobrantes = divmod(float(participantes_ordenados[0]['LastTime']), 60)
        self.lblLastLap_1.setText(agregar_cero_si_es_necesario(int(minutos)) + ":{0:.3f}".format(segundos_sobrantes))

        #Participante 2
        self.lblPosition_2.setText(str(participantes_ordenados[1]['Position']))
        self.lblID_2.setText(str(participantes_ordenados[1]['CarIdx']))
        self.lblNombre_2.setText(ir['DriverInfo']['Drivers'][participantes_ordenados[1]['CarIdx']]['UserName'])
        minutos, segundos_sobrantes = divmod(float(participantes_ordenados[1]['FastestTime']), 60)
        self.lblFastLap_2.setText(agregar_cero_si_es_necesario(int(minutos)) + ":{0:.3f}".format(segundos_sobrantes))
        minutos, segundos_sobrantes = divmod(float(participantes_ordenados[1]['LastTime']), 60)
        self.lblLastLap_2.setText(agregar_cero_si_es_necesario(int(minutos)) + ":{0:.3f}".format(segundos_sobrantes))

        #Participante 3
        self.lblPosition_3.setText(str(participantes_ordenados[2]['Position']))
        self.lblID_3.setText(str(participantes_ordenados[2]['CarIdx']))
        self.lblNombre_3.setText(ir['DriverInfo']['Drivers'][participantes_ordenados[2]['CarIdx']]['UserName'])
        minutos, segundos_sobrantes = divmod(float(participantes_ordenados[2]['FastestTime']), 60)
        self.lblFastLap_3.setText(agregar_cero_si_es_necesario(int(minutos)) + ":{0:.3f}".format(segundos_sobrantes))
        minutos, segundos_sobrantes = divmod(float(participantes_ordenados[2]['LastTime']), 60)
        self.lblLastLap_3.setText(agregar_cero_si_es_necesario(int(minutos)) + ":{0:.3f}".format(segundos_sobrantes))

        #Participante 4
        self.lblPosition_4.setText(str(participantes_ordenados[3]['Position']))
        self.lblID_4.setText(str(participantes_ordenados[3]['CarIdx']))
        self.lblNombre_4.setText(ir['DriverInfo']['Drivers'][participantes_ordenados[3]['CarIdx']]['UserName'])
        minutos, segundos_sobrantes = divmod(float(participantes_ordenados[3]['FastestTime']), 60)
        self.lblFastLap_4.setText(agregar_cero_si_es_necesario(int(minutos)) + ":{0:.3f}".format(segundos_sobrantes))
        minutos, segundos_sobrantes = divmod(float(participantes_ordenados[3]['LastTime']), 60)
        self.lblLastLap_4.setText(agregar_cero_si_es_necesario(int(minutos)) + ":{0:.3f}".format(segundos_sobrantes))

        #Participante 5
        self.lblPosition_5.setText(str(participantes_ordenados[4]['Position']))
        self.lblID_5.setText(str(participantes_ordenados[4]['CarIdx']))
        self.lblNombre_5.setText(ir['DriverInfo']['Drivers'][participantes_ordenados[4]['CarIdx']]['UserName'])
        minutos, segundos_sobrantes = divmod(float(participantes_ordenados[4]['FastestTime']), 60)
        self.lblFastLap_5.setText(agregar_cero_si_es_necesario(int(minutos)) + ":{0:.3f}".format(segundos_sobrantes))
        minutos, segundos_sobrantes = divmod(float(participantes_ordenados[4]['LastTime']), 60)
        self.lblLastLap_5.setText(agregar_cero_si_es_necesario(int(minutos)) + ":{0:.3f}".format(segundos_sobrantes))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.cargarDatos()
    MainWindow.show()
    sys.exit(app.exec_())
