# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'velocidadTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import irsdk, os

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 20, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lblVelocidad = QtWidgets.QLabel(Form)
        self.lblVelocidad.setGeometry(QtCore.QRect(80, 90, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lblVelocidad.setFont(font)
        self.lblVelocidad.setText("")
        self.lblVelocidad.setObjectName("lblVelocidad")
        ir = irsdk.IRSDK()
        ir.startup()
        stop = True
        # while stop:
        #     self.lblVelocidad.setText(str(round(ir['Speed']*3.6, 2)))
        #     os.system('cls')
        #     print("Velocidad: ", )
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Test de velocidad"))


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    
    sys.exit(app.exec_())